#!/usr/bin/env python3
"""Parse lychee JSON reports and fix broken links in markdown files."""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path


def load_report(path: str) -> dict:
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def get_redirect_fixes(report: dict) -> dict[str, str]:
    fixes: dict[str, str] = {}
    for _source, entries in report.get("redirect_map", {}).items():
        for entry in entries:
            original = entry["url"]
            chain = entry.get("status", {}).get("redirects", {}).get("redirects", [])
            if chain:
                final = chain[-1]["url"]
                if final != original:
                    fixes[original] = final
    return fixes


def get_wayback_fixes(report: dict) -> dict[str, str]:
    fixes: dict[str, str] = {}
    for _source, suggestions in report.get("suggestion_map", {}).items():
        for item in suggestions:
            original = item.get("original", "")
            suggestion = item.get("suggestion", "")
            if original and suggestion:
                fixes[original] = suggestion
    return fixes


def get_unfixable(report: dict, fixed_urls: set[str]) -> dict[str, list[dict]]:
    unfixable: dict[str, list[dict]] = {}
    for source, entries in report.get("error_map", {}).items():
        for entry in entries:
            url = entry["url"]
            if url not in fixed_urls:
                unfixable.setdefault(source, []).append(
                    {
                        "url": url,
                        "status": entry.get("status", {}).get("text", "Unknown"),
                    }
                )
    return unfixable


def build_replacement_pattern(fixes: dict[str, str]) -> re.Pattern[str]:
    sorted_urls = sorted(fixes.keys(), key=len, reverse=True)
    return re.compile("|".join(re.escape(url) for url in sorted_urls))


def apply_fixes(
    fixes: dict[str, str],
    root: Path,
) -> dict[str, list[tuple[str, str]]]:
    pattern = build_replacement_pattern(fixes)
    changes: dict[str, list[tuple[str, str]]] = {}

    for md_file in sorted(root.rglob("*.md")):
        if any(part.startswith(".") for part in md_file.parts):
            continue
        if "lychee" in md_file.parts:
            continue

        content = md_file.read_text(encoding="utf-8")
        seen: set[str] = set()
        file_fixes: list[tuple[str, str]] = []

        def replace(match: re.Match[str]) -> str:
            old = match.group(0)
            new = fixes[old]
            if old not in seen:
                file_fixes.append((old, new))
                seen.add(old)
            return new

        new_content = pattern.sub(replace, content)
        if new_content != content:
            md_file.write_text(new_content, encoding="utf-8")
            changes[str(md_file.relative_to(root))] = file_fixes

    return changes


def url_cell(url: str, max_len: int = 80) -> str:
    if len(url) <= max_len:
        return url
    return url[: max_len - 3] + "..."


def generate_pr_summary(
    redirect_fixes: dict[str, str],
    wayback_fixes: dict[str, str],
    changes: dict[str, list[tuple[str, str]]],
    unfixable: dict[str, list[dict]],
) -> str:
    lines: list[str] = [
        "## Auto-Fix Broken Links\n",
        "This PR was automatically generated by the link checker workflow.",
        "**Please review the changes before merging.**\n",
        "### Summary\n",
        f"- **{len(redirect_fixes)}** redirected URL(s) updated to final destination",
        f"- **{len(wayback_fixes)}** dead URL(s) replaced with Wayback Machine archives",
        f"- **{sum(len(v) for v in changes.values())}** total replacement(s) "
        f"across **{len(changes)}** file(s)\n",
    ]

    if redirect_fixes:
        lines += [
            "### Redirected URLs\n",
            "| Old URL | New URL |",
            "|---------|---------|",
        ]
        for old, new in sorted(redirect_fixes.items()):
            lines.append(f"| {url_cell(old)} | {url_cell(new)} |")
        lines.append("")

    if wayback_fixes:
        lines += [
            "### Dead URLs replaced with Wayback Machine archives\n",
            "| Dead URL | Archived URL |",
            "|----------|--------------|",
        ]
        for old, new in sorted(wayback_fixes.items()):
            lines.append(f"| {url_cell(old)} | {url_cell(new)} |")
        lines.append("")

    if unfixable:
        count = sum(len(v) for v in unfixable.values())
        lines += [
            f"### {count} link(s) could not be auto-fixed\n",
            "These require manual attention; a separate issue has been created.\n",
        ]
        for _source, entries in sorted(unfixable.items()):
            for entry in entries:
                lines.append(f"- `{entry['url']}` ({entry['status']})")
        lines.append("")

    return "\n".join(lines)


def generate_unfixable_report(unfixable: dict[str, list[dict]]) -> str:
    lines: list[str] = [
        "## Broken Links Requiring Manual Fix\n",
        "The following links could not be automatically fixed "
        "(no redirect detected and no Wayback Machine archive available).\n",
    ]
    for source, entries in sorted(unfixable.items()):
        lines.append(f"### `{source}`\n")
        for entry in entries:
            lines.append(f"- [ ] {entry['url']} -- {entry['status']}")
        lines.append("")

    return "\n".join(lines)


def set_output(name: str, value: str) -> None:
    path = os.environ.get("GITHUB_OUTPUT")
    if path:
        with open(path, "a", encoding="utf-8") as f:
            f.write(f"{name}={value}\n")
    print(f"  ::output:: {name}={value}")


def main() -> None:
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <lychee-report.json>", file=sys.stderr)
        sys.exit(1)

    report = load_report(sys.argv[1])
    root = Path(".")
    out_dir = Path("lychee")
    out_dir.mkdir(exist_ok=True)

    redirect_fixes = get_redirect_fixes(report)
    wayback_fixes = get_wayback_fixes(report)

    all_fixes: dict[str, str] = {}
    all_fixes.update(wayback_fixes)
    all_fixes.update(redirect_fixes)

    print(f"Redirect fixes : {len(redirect_fixes)}")
    print(f"Wayback fixes  : {len(wayback_fixes)}")

    unfixable = get_unfixable(report, set(all_fixes.keys()))

    if not all_fixes:
        print("No auto-fixable links found.")
        set_output("fixes_applied", "false")
        if unfixable:
            (out_dir / "unfixed-links.md").write_text(
                generate_unfixable_report(unfixable),
                encoding="utf-8",
            )
            set_output("has_unfixable", "true")
        else:
            set_output("has_unfixable", "false")
        return

    changes = apply_fixes(all_fixes, root)
    print(f"Files modified  : {len(changes)}")
    for filepath, fixes in sorted(changes.items()):
        for old, new in fixes:
            print(f"  {filepath}: {old} -> {new}")

    (out_dir / "fix-summary.md").write_text(
        generate_pr_summary(redirect_fixes, wayback_fixes, changes, unfixable),
        encoding="utf-8",
    )
    if unfixable:
        (out_dir / "unfixed-links.md").write_text(
            generate_unfixable_report(unfixable),
            encoding="utf-8",
        )

    set_output("fixes_applied", "true" if changes else "false")
    set_output("has_unfixable", "true" if unfixable else "false")


if __name__ == "__main__":
    main()
